USE HR;


-- Show the data from employee table 
SELECT *
FROM EMPLOYEES; --columns 12 , rows 107

SELECT *
FROM COUNTRIES; --columns ? , rows ? 

SELECT *
FROM JOB_HISTORY; --columns ? , rows ? 

SELECT *
FROM JOBS; --columns ? , rows ? 

SELECT *
FROM DEPARTMENTS; --columns ? , rows ? 

SELECT *
FROM LOCATIONS; --columns ? , rows ? 

SELECT *
FROM REGIONS; --columns ? , rows ? 

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS

SELECT CITY
FROM LOCATIONS

SELECT REGION_NAME
FROM REGIONS

SELECT SALARY
FROM EMPLOYEES
WHERE SALARY > 10000;

SELECT DEPARTMENT_NAME AS "Department's name is " , MANAGER_ID AS "ID'S"
FROM DEPARTMENTS

SELECT DEPARTMENT_NAME, MANAGER_ID
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME = 'sales'

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME = 'John'

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME = 'David'

SELECT *
FROM EMPLOYEES
WHERE NOT SALARY != 3000

SELECT *
FROM EMPLOYEES
WHERE SALARY != 3000

SELECT * 
FROM EMPLOYEES
WHERE SALARY > 5000
AND FIRST_NAME = 'David'

SELECT *
FROM EMPLOYEES
WHERE SALARY > 5000 
AND SALARY < 10000

SELECT *
FROM EMPLOYEES
WHERE SALARY = 5000 
OR SALARY = 10000

SELECT *
FROM EMPLOYEES
WHERE SALARY IN (5000,10000,12000)  ---FOR MULTIPLE OR CONDITIONS 





